### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by mic066** [electricityforprogress/BiodataSonificationBreadboardKit#1]
Seems like there is a sort of problem with the menu. I can enter the menu via the push button, but LEDs stop flashing when turning the pot a couple of times (it's actually very random: sometimes I can scroll the menu once, some times twice, sometimes never). Even though LEDs don't flash, I can enter the submenu, but only for led number 1 (threshold mode) and led number 4 (brightness mode). I guess there is something strange either in the "checkButton" or "checkMenu" functions, but I cannot find the problem. Has anyone had and fixed this problem?

**Comment by aspidonia** [comment]
I ran into similar issues which made using the physical menu navigation frustrating and irregular. I am just starting to get reoriented with my build but it looks like what I did was eliminate the 
**" leds[prevValue].stop_fade(); "** under peripherals. 

I also changed the brightness of the menu and submenus to make it more distinctive.

I also don't know what I'm doing, but somehow it seems to work better.

Through the lens of an end user of this as a product, I think I mostly understand the design considerations and limitations of getting to have a few things to be able to change, and a way to change them.

that being said, it feels like a limiting compromise and I've found a better creative and exploratory flow accessing and manipulating variables via the code vs the physical menu.

**Comment by electricityforprogress** [comment]
Sorry that the menu has been challenging for many users.  I have had a 50% response for users who have the menus working fine.  Checkout my new Biodata Feather repository, using an ESP32 module for Bluetooth and wifi, the Menu mode functions smoothly in the new codebase.  Also Manuel's code sometimes works bettter for users:  https://github.com/electricityforprogress/midi-biodata
