### ISSUE TITLE
Schematics not opening?

### ISSUE THREAD

**Issue by pzelchenko** [electricityforprogress/BiodataSonificationBreadboardKit#2]
Spent about a week popping in here downloading the sch and brd files to try to get a sensible schematic of this project. Not having much luck opening the Eagle XML files on any of the apps we have available in this lab.

This seems like a pretty simple project. The step-by-step protoboard document seems like gilding the lily. Any chance you could put up a simple bitmap or vector image of a rudimentary schematic?

**Comment by electricityforprogress** [comment]
Hey sorry this is an old project.  Try the main MIDI Sprout repository for a simple schematic https://github.com/electricityforprogress/MIDIsprout
