### ISSUE TITLE
Biodata sonification code

### ISSUE THREAD

**Issue by rvouger** [electricityforprogress/BiodataSonificationBreadboardKit#4]
I tired uploading the code after building the kit with an uno r3, there was a few problems with things not declared in the scope and things does not name a type. I'm not so sure how to fix these problems, has anyone else tried to run this recently?

**Comment by rvouger** [comment]
Arduino: 1.8.19 (Mac OS X), Board: "Arduino Uno"


these are the error messages:








hghghgh:35:1: error: 'Bounce' does not name a type; did you mean 'tone'?
 Bounce button = Bounce(); //debounce button using Bounce2
 ^~~~~~
 tone
hghghgh:75:1: error: 'LEDFader' does not name a type
 LEDFader leds[LED_NUM] = { // 6 LEDs (perhaps 2 RGB LEDs)
 ^~~~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void setup()':
hghghgh:105:3: error: 'button' was not declared in this scope
   button.attach(buttonPin);
   ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:105:3: note: suggested alternative: 'buttonPin'
   button.attach(buttonPin);
   ^~~~~~
   buttonPin
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void setNote(int, int, long int, int)':
hghghgh:158:17: error: 'leds' was not declared in this scope
             if(!leds[j].is_fading()) { rampUp(i, maxBrightness, duration);  break; }
                 ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:158:17: note: suggested alternative: 'gets'
             if(!leds[j].is_fading()) { rampUp(i, maxBrightness, duration);  break; }
                 ^~~~
                 gets
hghghgh:162:17: error: 'leds' was not declared in this scope
             if(!leds[j].is_fading()) { rampUp(i, maxBrightness, duration);  break; }
                 ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:162:17: note: suggested alternative: 'gets'
             if(!leds[j].is_fading()) { rampUp(i, maxBrightness, duration);  break; }
                 ^~~~
                 gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void rampUp(int, int, int)':
hghghgh:269:1: error: 'LEDFader' was not declared in this scope
 LEDFader *led = &leds[ledPin];
 ^~~~~~~~
hghghgh:269:11: error: 'led' was not declared in this scope
 LEDFader *led = &leds[ledPin];
           ^~~
hghghgh:269:18: error: 'leds' was not declared in this scope
 LEDFader *led = &leds[ledPin];
                  ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:269:18: note: suggested alternative: 'gets'
 LEDFader *led = &leds[ledPin];
                  ^~~~
                  gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void rampDown(int, int, int)':
hghghgh:276:3: error: 'LEDFader' was not declared in this scope
   LEDFader *led = &leds[ledPin];
   ^~~~~~~~
hghghgh:276:13: error: 'led' was not declared in this scope
   LEDFader *led = &leds[ledPin];
             ^~~
hghghgh:276:20: error: 'leds' was not declared in this scope
   LEDFader *led = &leds[ledPin];
                    ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:276:20: note: suggested alternative: 'gets'
   LEDFader *led = &leds[ledPin];
                    ^~~~
                    gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void checkLED()':
hghghgh:284:5: error: 'LEDFader' was not declared in this scope
     LEDFader *led = &leds[i];
     ^~~~~~~~
hghghgh:284:15: error: 'led' was not declared in this scope
     LEDFader *led = &leds[i];
               ^~~
hghghgh:284:22: error: 'leds' was not declared in this scope
     LEDFader *led = &leds[i];
                      ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:284:22: note: suggested alternative: 'gets'
     LEDFader *led = &leds[i];
                      ^~~~
                      gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void checkButton()':
hghghgh:291:3: error: 'button' was not declared in this scope
   button.update();
   ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:291:3: note: suggested alternative: 'buttonPin'
   button.update();
   ^~~~~~
   buttonPin
hghghgh:295:35: error: 'leds' was not declared in this scope
     for(byte j=0;j<LED_NUM;j++) { leds[j].stop_fade(); leds[j].set_value(0); } //off LEDs
                                   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:295:35: note: suggested alternative: 'gets'
     for(byte j=0;j<LED_NUM;j++) { leds[j].stop_fade(); leds[j].set_value(0); } //off LEDs
                                   ^~~~
                                   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void checkMenu()':
hghghgh:350:9: error: 'leds' was not declared in this scope
         leds[prevValue].stop_fade();
         ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:350:9: note: suggested alternative: 'gets'
         leds[prevValue].stop_fade();
         ^~~~
         gets
hghghgh:378:9: error: 'leds' was not declared in this scope
         leds[prevValue].stop_fade();
         ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:378:9: note: suggested alternative: 'gets'
         leds[prevValue].stop_fade();
         ^~~~
         gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void checkBattery()':
hghghgh:408:37: error: 'leds' was not declared in this scope
       for(byte j=0;j<LED_NUM;j++) { leds[j].stop_fade(); leds[j].set_value(0); }  //reset leds, power savings
                                     ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:408:37: note: suggested alternative: 'gets'
       for(byte j=0;j<LED_NUM;j++) { leds[j].stop_fade(); leds[j].set_value(0); }  //reset leds, power savings
                                     ^~~~
                                     gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void pulse(int, int, int)':
hghghgh:421:2: error: 'LEDFader' was not declared in this scope
  LEDFader *led = &leds[ledPin];
  ^~~~~~~~
hghghgh:421:12: error: 'led' was not declared in this scope
  LEDFader *led = &leds[ledPin];
            ^~~
hghghgh:421:19: error: 'leds' was not declared in this scope
  LEDFader *led = &leds[ledPin];
                   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:421:19: note: suggested alternative: 'gets'
  LEDFader *led = &leds[ledPin];
                   ^~~~
                   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void bootLightshow()':
hghghgh:433:5: error: 'LEDFader' was not declared in this scope
     LEDFader *led = &leds[i-1];
     ^~~~~~~~
hghghgh:433:15: error: 'led' was not declared in this scope
     LEDFader *led = &leds[i-1];
               ^~~
hghghgh:433:22: error: 'leds' was not declared in this scope
     LEDFader *led = &leds[i-1];
                      ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:433:22: note: suggested alternative: 'gets'
     LEDFader *led = &leds[i-1];
                      ^~~~
                      gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void thresholdMode()':
hghghgh:476:5: error: 'button' was not declared in this scope
     button.update();
     ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:476:5: note: suggested alternative: 'buttonPin'
     button.update();
     ^~~~~~
     buttonPin
hghghgh:483:3: error: 'leds' was not declared in this scope
   leds[prevValue].stop_fade();
   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:483:3: note: suggested alternative: 'gets'
   leds[prevValue].stop_fade();
   ^~~~
   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void scaleMode()':
hghghgh:500:7: error: 'leds' was not declared in this scope
       leds[prevScale].stop_fade();
       ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:500:7: note: suggested alternative: 'gets'
       leds[prevScale].stop_fade();
       ^~~~
       gets
hghghgh:510:5: error: 'button' was not declared in this scope
     button.update();
     ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:510:5: note: suggested alternative: 'buttonPin'
     button.update();
     ^~~~~~
     buttonPin
hghghgh:517:3: error: 'leds' was not declared in this scope
   leds[prevValue].stop_fade();
   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:517:3: note: suggested alternative: 'gets'
   leds[prevValue].stop_fade();
   ^~~~
   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void channelMode()':
hghghgh:538:5: error: 'button' was not declared in this scope
     button.update();
     ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:538:5: note: suggested alternative: 'buttonPin'
     button.update();
     ^~~~~~
     buttonPin
hghghgh:545:3: error: 'leds' was not declared in this scope
   leds[prevValue].stop_fade();
   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:545:3: note: suggested alternative: 'gets'
   leds[prevValue].stop_fade();
   ^~~~
   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void brightnessMode()':
hghghgh:564:5: error: 'button' was not declared in this scope
     button.update();
     ^~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:564:5: note: suggested alternative: 'buttonPin'
     button.update();
     ^~~~~~
     buttonPin
hghghgh:571:3: error: 'leds' was not declared in this scope
   leds[prevValue].stop_fade();
   ^~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:571:3: note: suggested alternative: 'gets'
   leds[prevValue].stop_fade();
   ^~~~
   gets
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino: In function 'void analyzeSample()':
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:632:37: warning: invalid conversion from 'int' to 'int*' [-fpermissive]
        setnote = scaleNote(setnote, *scale[currScale], root);  //scale the note
                                     ^~~~~~~~~~~~~~~~~
/Users/cherrysong/Documents/Arduino/hghghgh/hghghgh.ino:657:5: note:   initializing argument 2 of 'int scaleNote(int, int*, int)'
 int scaleNote(int note, int scale[], int root) {
     ^~~~~~~~~
exit status 1
'Bounce' does not name a type; did you mean 'tone'?


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sickozell** [comment]
I had problems compiling it with arduino nano at line 632:
setnote = scaleNote(setnote, *scale[currScale], root);  //scale the note
That * seemed to be the problem, but I don't know how to fix pointers issues, so I'm trying to write a new routine to calculate scales without them

**Comment by electricityforprogress** [comment]
Hey I have gotten a couple comments about the setNote pointer.  The main MIDI Sprout code and my new Biodata Feather  code do not include the star.  I have updated the codebase to reflect a direct reference to the scaleNote array.
