### ISSUE TITLE
A

### ISSUE THREAD

**Issue by matiaraoz** [electricityforprogress/BiodataSonificationBreadboardKit#6]
Hey!

Thank you so much for all your instructions to make this kit!

I'm having some issues uploading the sketch, this error keeps coming up:

avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_recv(): programmer is not responding

Do you know why this might be?

Thanks!

Mati

**Comment by sim272** [comment]
Hi @matiaraoz i have the same problem here, it seems that you resolve it am i right ?
