### ISSUE TITLE
Issue with getting the project to work with computer

### ISSUE THREAD

**Issue by laxelh** [electricityforprogress/BiodataSonificationBreadboardKit#7]
Hello, 

I have built the project and uploaded the code successfully but I am having an issue with getting a sound output. I don't own a modular synth but I bought a Midi to USB cable to use with garageband. When I plug the cable into the board and my computer, the computer detects it as a Midi input but when I switch the board on and try to get it to output something, it doesn't work. Any suggestions on how I can get it to work?

**Comment by Gardemia** [comment]
Is because you need to conect the port number 2 of the midi (the center of the midi) to ground.
![753F3257-8A19-4DEE-891A-1E98D476C3E0](https://user-images.githubusercontent.com/112072135/186618584-06db2a60-b287-4693-814c-1724b1ad0eec.jpeg)

**Comment by Xvex34** [comment]
Hello, im a diyi guy from the midwest and my girlfriend wants to hear her plants sing to her. 

My goal is to complete this project for her birthday this November, but hit a bump in the road…  

Can you use this project on iPhone garage band? I got the MIDI cable to usb to iPhone converter cable. And yes I grounded the MIDI port on the bread board but no sound.

please let me know 

Thanks.

**Comment by electricityforprogress** [comment]
MIDI outputs DO NOT require ground connection ... in fact the most important part about MIDI is electrical isoloation.  Only pins 4 and 5 are needed for the sink (TX output) and the pull up voltage through a resistor (the orange and red lines in the image above)

@Xvex34 If you want to connect to an iphone, you should use the new version of the device which utilizes an Adafruit Feather ESP32 and can connect using Bluetooth very easily (no cable). 

Careful with cheap USB-MIDI cables ... they simply DO NOT WORK.  I use the Emu XMIDI 1x1 as a simple USB-MIDI device.  Use a known brand name and you should be fine.
